---
- name: Various tasks for my lab env
  hosts: all
  become: yes
  tasks:
     - name: Reset Nodes to Snapshot
       command: /usr/sbin/qm rollback "{{ item }}" preupgrade
       loop:
        - 102
        - 106
        - 107
        - 108
        - 110
        - 111
        - 112
        - 113
       tags:
        - rollback
     - name: Start Nodes
       command: /usr/sbin/qm start "{{ item }}"
       loop:
        - 102
        - 106
        - 107
        - 108
        - 110
        - 111
        - 112
        - 113
       tags:
        - start
     - name: Stop  Nodes
       command: /usr/sbin/qm stop "{{ item }}"
       loop:
        - 102
        - 106
        - 107
        - 108
        - 110
        - 111
        - 112
        - 113
       tags:
        - stop
