---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
<<<<<<< HEAD
    - name: Finding yumtx files in /tmp
      find:
        paths: /tmp/
        patterns: '*.yumtx'
        age: 1m
        recurse: no
      register: yumtx
    - name: Delete yumtx files from /tmp
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ yumtx.files }}"
#      when: yumtx.files == True
=======
    - name: find files older than 30 days
      find:
        paths: /var/crash/
        patterns: '127.0.0.1*'
        age: 30d
        recurse: no
      register: files_to_be_removed
    - name: delete files older than 30 days
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_be_removed.files }}"

    - name: Ansible find directories older than x time
      find:
        paths: /var/crash
        age: 30d
        file_type: directory
      register: directories_to_be_removed

    - name: delete directories older than x time
      file:
        path: /var/crash/
        state: absent
        recurse: no
      with_items: "{{ directories_to_be_removed }}"

    - debug:
        var: directories_to_be_removed.files
        var: files_to_be_removed.files
>>>>>>> 3c1d3d3cefc5a6aa41b61c555a78f3491e6e5619
