---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: Register Satellite RHEL 6,7,8
    command: subscription-manager register --org=13906745 --activationkey=$keyhere
    ignore_errors: true
    tags:
      - rhel6
      - rhel7
      - rhel8

  - name: Register Satellite RHEL 9 Beta
    command: subscription-manager register --org=13906745 --activationkey=$keyhere
    ignore_errors: true
    tags:
      - rhel9
