---
- hosts: all
  become: yes
#  vars:
#    reg: vars/registration_vars.yml
  tasks:
  - name: Register Satellite RHEL 6,7,8,9
    include_vars: 'registration_vars.yml'
    command: subscription-manager register --org="{{ org }}" --activationkey="{{ reg_key6 }}"
    ignore_errors: true
    tags:
      - register
    when: (ansible_distribution == 'RedHat' and ansible_distribution_major_version == '6' or ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8' or ansible_distribution_major_version == '9')

  - name: Unregister Satellite RHEL 6,7,8,9
    command: subscription-manager unregister
    ignore_errors: true
    tags:
      - unregister
    when: (ansible_distribution == 'RedHat' and ansible_distribution_major_version == '6' or ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8' or ansible_distribution_major_version == '9')
