---
- hosts: all
  become: yes
  tasks:
  - name: Register Satellite RHEL 6,7,8
    command: subscription-manager register --org="{{ org }}" --activationkey="{{ reg_key6 }}"
    ignore_errors: true
    vars_files:
      - "vars/registration_vars.yml"
    tags:
      - rhel6
      - rhel7
      - rhel8
    when:
        ansible_distribution == 'RedHat' and ansible_distribution_major_version == '6' or ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8'

  - name: Register Satellite RHEL 9 Beta
    command: subscription-manager register --org= --activationkey=
    ignore_errors: true
    tags:
      - rhel9
    when:
        ansible_distribution == 'RedHat' and ansible_distribution_major_version == '9'
