---
- hosts: all
  become: yes
  tasks:
  - name: Register Satellite RHEL 6,7,8,9
    command: subscription-manager register --org=13906745 --activationkey=jwalters-key
    ignore_errors: true
    tags:
      - register
#      - rhel6
#      - rhel7
#      - rhel8
#      - rhel9
    when: (ansible_distribution == 'RedHat' and ansible_distribution_major_version == '6' or ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8' or ansible_distribution_major_version == '9')

  - name: Unregister Satellite RHEL 6,7,8,9
    command: subscription-manager unregister
    ignore_errors: true
    tags:
      - unregister
#      - rhel6
#      - rhel7
#      - rhel8
#      - rhel9
    when: (ansible_distribution == 'RedHat' and ansible_distribution_major_version == '6' or ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8' or ansible_distribution_major_version == '9')
