---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
  - name: update all yum based hosts
    register: yum_update_out
    yum:
      name: "*"
      state: latest
#      update_cache: "yes"
    throttle: 20

  - name: Check if reboot is needed RHEL6
    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "6"
    command: "/usr/bin/needs-restarting"
    register: reboot_needed6
    ignore_errors: true
    changed_when: false
    failed_when: reboot_needed6.rc == 2

  - name: Check if reboot is needed RHEL7+
    when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7") or
          (ansible_distribution == "RedHat" and ansible_distribution_major_version == "8") or
          (ansible_distribution == "RedHat" and ansible_distribution_major_version == "9")
    command: "/usr/bin/needs-restarting -r"
    register: reboot_needed
    ignore_errors: true
    changed_when: false
    failed_when: reboot_needed.rc == 2

  - name: Reboot Server RHEL6
    reboot:
      msg: "Reboot initiated by Ansible for BAU monthly patching activity"
      pre_reboot_delay: 0
      post_reboot_delay: 60
      reboot_timeout: 600
      test_command: "whoami"
    throttle: 20
    when: reboot_needed6.rc == 1

  - name: Reboot Server RHEL7+
    reboot:
      msg: "Reboot initiated by Ansible for BAU monthly patching activity"
      pre_reboot_delay: 0
      post_reboot_delay: 60
      reboot_timeout: 600
      test_command: "whoami"
    throttle: 20
    when: reboot_needed.rc == 1

# For debugging, uncomment below if needed.
#  - name: print update results
#    debug:
#      msg: yum_update_out | select("search", "results") | list
#      var: yum_update_out
